config/routes.rb
Rails.application.routes.draw do
  get 'exemplos/index'

  get 'about/index'

  get 'diagrama/index'

  root 'index#index'

  resources :index
  resources :usuarios
  resources :posts
  resources :pets
  resources :localizacaos
  resources :enderecos
  resources :bairros
  resources :cidades
  resources :estados
  resources :pais

  resources :consulta_banco do
    get 'consultar', on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bairro.rb
class Bairro < ApplicationRecord
  belongs_to :cidade
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  has_one :pais
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :bairro
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :pai
  has_one :cidade
end

app/models/localizacao.rb
class Localizacao < ApplicationRecord
  belongs_to :endereco
end

app/models/pai.rb
class Pai < ApplicationRecord
  has_many :estados
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :localizacao
  belongs_to :pet
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :posts
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:logradouro, :cep, :bairro_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/diagrama_helper.rb
module DiagramaHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/exemplos_helper.rb
module ExemplosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/enderecos/_form.html.erb
<%= form_for(endereco) do |f| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logradouro %>
    <%= f.text_field :logradouro %>
  </div>

  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div class="field">
    <%= f.label :bairro_id %>
    <%= f.select :bairro_id, options_for_select(Bairro.all.map{|s|[s.nome, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Logradouro</th>
      <th>Cep</th>
      <th>Bairro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.logradouro %></td>
        <td><%= endereco.cep %></td>
        <td><%= endereco.bairro.nome %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logradouro:</strong>
  <%= @endereco.logradouro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @endereco.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @endereco.bairro.nome %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>