config/routes.rb
Rails.application.routes.draw do
  get 'exemplos/index'

  get 'about/index'

  get 'diagrama/index'

  root 'index#index'

  resources :index
  resources :usuarios
  resources :posts
  resources :pets
  resources :localizacaos
  resources :enderecos
  resources :bairros
  resources :cidades
  resources :estados
  resources :pais

  resources :consulta_banco do
    get 'consultar', on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bairro.rb
class Bairro < ApplicationRecord
  belongs_to :cidade
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  has_one :pais
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :bairro
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :pai
  has_one :cidade
end

app/models/localizacao.rb
class Localizacao < ApplicationRecord
  belongs_to :endereco
end

app/models/pai.rb
class Pai < ApplicationRecord
  has_many :estados
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :localizacao
  belongs_to :pet
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :posts
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:nome, :estado_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/diagrama_helper.rb
module DiagramaHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/exemplos_helper.rb
module ExemplosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/cidades/_form.html.erb
<%= form_for(cidade) do |f| %>
  <% if cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :estado_id %>
    <%= f.select :estado_id, options_for_select(Estado.all.map{|s|[s.nome, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cidades.each do |cidade| %>
      <tr>
        <td><%= cidade.nome %></td>
        <td><%= cidade.estado.nome %></td>
        <td><%= link_to 'Show', cidade %></td>
        <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
        <td><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cidade', new_cidade_path %>

app/views/cidades/new.html.erb
<h1>New Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cidade.estado.nome %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>