config/routes.rb
Rails.application.routes.draw do
  get 'exemplos/index'

  get 'about/index'

  get 'diagrama/index'

  root 'index#index'

  resources :index
  resources :usuarios
  resources :posts
  resources :pets
  resources :localizacaos
  resources :enderecos
  resources :bairros
  resources :cidades
  resources :estados
  resources :pais

  resources :consulta_banco do
    get 'consultar', on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bairro.rb
class Bairro < ApplicationRecord
  belongs_to :cidade
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  has_one :pais
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :bairro
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :pai
  has_one :cidade
end

app/models/localizacao.rb
class Localizacao < ApplicationRecord
  belongs_to :endereco
end

app/models/pai.rb
class Pai < ApplicationRecord
  has_many :estados
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :localizacao
  belongs_to :pet
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :posts
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nome, :sigla, :pai_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/diagrama_helper.rb
module DiagramaHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/exemplos_helper.rb
module ExemplosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/estados/_form.html.erb
<%= form_for(estado) do |f| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sigla %>
    <%= f.text_field :sigla %>
  </div>

  <div class="field">
    <%= f.label :pai_id %>
    <%= f.select :pai_id, options_for_select(Pai.all.map{|s|[s.nome, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.nome %></td>
        <td><%= estado.sigla %></td>
        <td><%= estado.pai.nome %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estado.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @estado.sigla %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @estado.pai.nome %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>