config/routes.rb
Rails.application.routes.draw do
  get 'exemplos/index'

  get 'about/index'

  get 'diagrama/index'

  root 'index#index'

  resources :index
  resources :usuarios
  resources :posts
  resources :pets
  resources :localizacaos
  resources :enderecos
  resources :bairros
  resources :cidades
  resources :estados
  resources :pais

  resources :consulta_banco do
    get 'consultar', on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bairro.rb
class Bairro < ApplicationRecord
  belongs_to :cidade
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  has_one :pais
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :bairro
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :pai
  has_one :cidade
end

app/models/localizacao.rb
class Localizacao < ApplicationRecord
  belongs_to :endereco
end

app/models/pai.rb
class Pai < ApplicationRecord
  has_many :estados
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :localizacao
  belongs_to :pet
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :posts
end

app/controllers/bairros_controller.rb
class BairrosController < ApplicationController
  before_action :set_bairro, only: [:show, :edit, :update, :destroy]

  # GET /bairros
  # GET /bairros.json
  def index
    @bairros = Bairro.all
  end

  # GET /bairros/1
  # GET /bairros/1.json
  def show
  end

  # GET /bairros/new
  def new
    @bairro = Bairro.new
  end

  # GET /bairros/1/edit
  def edit
  end

  # POST /bairros
  # POST /bairros.json
  def create
    @bairro = Bairro.new(bairro_params)

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to @bairro, notice: 'Bairro was successfully created.' }
        format.json { render :show, status: :created, location: @bairro }
      else
        format.html { render :new }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bairros/1
  # PATCH/PUT /bairros/1.json
  def update
    respond_to do |format|
      if @bairro.update(bairro_params)
        format.html { redirect_to @bairro, notice: 'Bairro was successfully updated.' }
        format.json { render :show, status: :ok, location: @bairro }
      else
        format.html { render :edit }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1
  # DELETE /bairros/1.json
  def destroy
    @bairro.destroy
    respond_to do |format|
      format.html { redirect_to bairros_url, notice: 'Bairro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bairro
      @bairro = Bairro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bairro_params
      params.require(:bairro).permit(:nome, :cidade_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/diagrama_helper.rb
module DiagramaHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/exemplos_helper.rb
module ExemplosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pais_helper.rb
module PaisHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/bairros/_form.html.erb
<%= form_for(bairro) do |f| %>
  <% if bairro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bairro.errors.count, "error") %> prohibited this bairro from being saved:</h2>

      <ul>
      <% bairro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :cidade_id %>
    <%= f.select :cidade_id, options_for_select(Cidade.all.map{|s|[s.nome, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bairros/edit.html.erb
<h1>Editing Bairro</h1>

<%= render 'form', bairro: @bairro %>

<%= link_to 'Show', @bairro %> |
<%= link_to 'Back', bairros_path %>

app/views/bairros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bairros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bairros.each do |bairro| %>
      <tr>
        <td><%= bairro.nome %></td>
        <td><%= bairro.cidade.nome %></td>
        <td><%= link_to 'Show', bairro %></td>
        <td><%= link_to 'Edit', edit_bairro_path(bairro) %></td>
        <td><%= link_to 'Destroy', bairro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bairro', new_bairro_path %>

app/views/bairros/new.html.erb
<h1>New Bairro</h1>

<%= render 'form', bairro: @bairro %>

<%= link_to 'Back', bairros_path %>

app/views/bairros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @bairro.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @bairro.cidade.nome %>
</p>

<%= link_to 'Edit', edit_bairro_path(@bairro) %> |
<%= link_to 'Back', bairros_path %>